name: Feature
description: Propose a new feature or gameplay/system improvement
title: "feat: <description>"
labels:
  - feat
assignees:
  - calvinmcelvain
  - Collin-McElvain

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What are we adding?
      placeholder: Add a short description of the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why does this feature matter?
      placeholder: (Optional) Explain the gameplay, technical, or UX reason

  - type: textarea
    id: implementation
    attributes:
      label: Possible Implementation
      description: Optional notes on how this could work
      placeholder: (Optional) Systems, algorithms, files, ideas, etc.